puts "The students of my cohort at Makers Academy"
puts "------------------------"
puts "Victoria Barr"
puts "Karin Nielsen"
puts "Andrew Snead"
puts "Nicole Tredway"
puts "Rachel Nolan"
puts "Tim Scully"
puts "Craig Horsborough"
puts "Camilla van Klinken"
puts "Andrew Hercules"
puts "Peter Saxton"
puts "Dario Daprile"
puts "Anna Schechter"
puts "Denise Yu"
puts "Alex Fakhri"
puts "Bernard Mordan"